# Generated by Django 3.2.11 on 2022-01-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Yordam',
            new_name='Teacher',
        ),
    ]
