# Generated by Django 3.2.11 on 2022-01-29 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_fullname_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='role_eng',
            field=models.CharField(default="rolsiz", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='role_ru',
            field=models.CharField(default="rolsiz", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='role_uz',
            field=models.CharField(default="rolsiz", max_length=30),
            preserve_default=False,
        ),
    ]
