# Generated by Django 3.2.11 on 2022-01-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yordam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', models.CharField(max_length=100)),
                ('text_eng', models.CharField(max_length=100)),
                ('text_ru', models.CharField(max_length=100)),
            ],
        ),
    ]
